name: Rust

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          override: true

    - name: Install dependencies
      run: cargo install cargo-bundle

    - name: Bundle
      run: cargo bundle --release
